name: E2E Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: The E2E tests can be run directly on the github branch or on the development environment URL 
        required: true
        options:
          - selected-branch
          - dev-url
        default: selected-branch
      # crossBrowser: 
      #   type: boolean
      #   description: Would you like to run the tests for all major browsers? (Chrome, Edge and Firefox)
      #   required: true
jobs:
  run-selected-branch-tests:
    if: github.event.inputs.environment == 'selected-branch'
    runs-on:
      - self-hosted
      - linux
      - x64
      - dev
      - docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install yarn
        run: npm install -g yarn
      - name: Run Solutions Tests
        uses: cypress-io/github-action@v2
        env:
          REACT_APP_CONTENT_URL: 'https://content.com/'
        with:
          start: yarn run start
          wait-on: http://localhost:3000
          wait-on-timeout: 6000
          # record: true
          # group: chrome
          # parallel: true
          command: yarn run test:e2e
      - name: Save video recordings to an artifact on failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Save screenshots to an artifact on failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

  run-dev-url-tests:
    if: github.event.inputs.environment == 'dev-url'
    runs-on:
      - self-hosted
      - linux
      - x64
      - dev
      - docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install yarn
        run: npm install -g yarn
      - name: Run Solutions Tests
        uses: cypress-io/github-action@v2
        env:
          REACT_APP_CONTENT_URL: 'backend.url'
        with:
          # start: yarn run start
          # wait-on: http://localhost:3000
          # wait-on-timeout: 6000
          # record: true
          # group: chrome
          # parallel: true
          command: yarn run test:e2e --config baseUrl="google.com"
      - name: Save video recordings to an artifact on failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Save screenshots to an artifact on failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
